//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.ErrorLogServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ErrorLogServices.IErrorLogServices")]
    public interface IErrorLogServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErrorLogServices/Log", ReplyAction="http://tempuri.org/IErrorLogServices/LogResponse")]
        void Log(string username, string message, string innerException);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErrorLogServices/Log", ReplyAction="http://tempuri.org/IErrorLogServices/LogResponse")]
        System.Threading.Tasks.Task LogAsync(string username, string message, string innerException);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IErrorLogServicesChannel : WebPortal.ErrorLogServices.IErrorLogServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ErrorLogServicesClient : System.ServiceModel.ClientBase<WebPortal.ErrorLogServices.IErrorLogServices>, WebPortal.ErrorLogServices.IErrorLogServices {
        
        public ErrorLogServicesClient() {
        }
        
        public ErrorLogServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ErrorLogServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorLogServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorLogServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Log(string username, string message, string innerException) {
            base.Channel.Log(username, message, innerException);
        }
        
        public System.Threading.Tasks.Task LogAsync(string username, string message, string innerException) {
            return base.Channel.LogAsync(username, message, innerException);
        }
    }
}
