//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
            this.Transactions1 = new HashSet<Transaction>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Username { get; set; }
        public System.DateTime DateOpened { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public decimal Balance { get; set; }
        public string Currency { get; set; }
        public string Remarks { get; set; }
    
        public virtual Currency Currency1 { get; set; }
        public virtual AccountType AccountType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Transaction> Transactions1 { get; set; }
    }
}
