//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedTermAccount
    {
        public int AccountID { get; set; }
        public Nullable<decimal> MaturityAmount { get; set; }
        public Nullable<decimal> IncomeTaxDeduction { get; set; }
        public Nullable<decimal> AccumulatedInterest { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<int> RateID { get; set; }
        public Nullable<bool> IsExpired { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual InterestRate InterestRate { get; set; }
    }
}
