//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManager.AppointmentServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppointmentServices.IAppointmentServices")]
    public interface IAppointmentServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentServices/ListAppointments", ReplyAction="http://tempuri.org/IAppointmentServices/ListAppointmentsResponse")]
        System.Collections.Generic.List<WcfServiceDSABank.AppointmentView> ListAppointments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentServices/ListAppointments", ReplyAction="http://tempuri.org/IAppointmentServices/ListAppointmentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WcfServiceDSABank.AppointmentView>> ListAppointmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentServices/FilterAppointmentList", ReplyAction="http://tempuri.org/IAppointmentServices/FilterAppointmentListResponse")]
        System.Collections.Generic.List<WcfServiceDSABank.AppointmentView> FilterAppointmentList(System.Nullable<bool> isAccepted, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentServices/FilterAppointmentList", ReplyAction="http://tempuri.org/IAppointmentServices/FilterAppointmentListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WcfServiceDSABank.AppointmentView>> FilterAppointmentListAsync(System.Nullable<bool> isAccepted, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentServices/Schedule", ReplyAction="http://tempuri.org/IAppointmentServices/ScheduleResponse")]
        void Schedule(WcfServiceDSABank.AppointmentView appointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentServices/Schedule", ReplyAction="http://tempuri.org/IAppointmentServices/ScheduleResponse")]
        System.Threading.Tasks.Task ScheduleAsync(WcfServiceDSABank.AppointmentView appointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentServices/Response", ReplyAction="http://tempuri.org/IAppointmentServices/ResponseResponse")]
        void Response(WcfServiceDSABank.AppointmentView appointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentServices/Response", ReplyAction="http://tempuri.org/IAppointmentServices/ResponseResponse")]
        System.Threading.Tasks.Task ResponseAsync(WcfServiceDSABank.AppointmentView appointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentServices/Delete", ReplyAction="http://tempuri.org/IAppointmentServices/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentServices/Delete", ReplyAction="http://tempuri.org/IAppointmentServices/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppointmentServicesChannel : BankManager.AppointmentServices.IAppointmentServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppointmentServicesClient : System.ServiceModel.ClientBase<BankManager.AppointmentServices.IAppointmentServices>, BankManager.AppointmentServices.IAppointmentServices {
        
        public AppointmentServicesClient() {
        }
        
        public AppointmentServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppointmentServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppointmentServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppointmentServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WcfServiceDSABank.AppointmentView> ListAppointments() {
            return base.Channel.ListAppointments();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WcfServiceDSABank.AppointmentView>> ListAppointmentsAsync() {
            return base.Channel.ListAppointmentsAsync();
        }
        
        public System.Collections.Generic.List<WcfServiceDSABank.AppointmentView> FilterAppointmentList(System.Nullable<bool> isAccepted, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end) {
            return base.Channel.FilterAppointmentList(isAccepted, start, end);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WcfServiceDSABank.AppointmentView>> FilterAppointmentListAsync(System.Nullable<bool> isAccepted, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end) {
            return base.Channel.FilterAppointmentListAsync(isAccepted, start, end);
        }
        
        public void Schedule(WcfServiceDSABank.AppointmentView appointment) {
            base.Channel.Schedule(appointment);
        }
        
        public System.Threading.Tasks.Task ScheduleAsync(WcfServiceDSABank.AppointmentView appointment) {
            return base.Channel.ScheduleAsync(appointment);
        }
        
        public void Response(WcfServiceDSABank.AppointmentView appointment) {
            base.Channel.Response(appointment);
        }
        
        public System.Threading.Tasks.Task ResponseAsync(WcfServiceDSABank.AppointmentView appointment) {
            return base.Channel.ResponseAsync(appointment);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
