//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManager.LogServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogServices.ILogServices")]
    public interface ILogServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogServices/DeleteError", ReplyAction="http://tempuri.org/ILogServices/DeleteErrorResponse")]
        void DeleteError(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogServices/DeleteError", ReplyAction="http://tempuri.org/ILogServices/DeleteErrorResponse")]
        System.Threading.Tasks.Task DeleteErrorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogServices/DeleteEvent", ReplyAction="http://tempuri.org/ILogServices/DeleteEventResponse")]
        void DeleteEvent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogServices/DeleteEvent", ReplyAction="http://tempuri.org/ILogServices/DeleteEventResponse")]
        System.Threading.Tasks.Task DeleteEventAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogServices/FilterErrorsList", ReplyAction="http://tempuri.org/ILogServices/FilterErrorsListResponse")]
        System.Collections.Generic.List<WcfServiceDSABank.ErrorView> FilterErrorsList(string query, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogServices/FilterErrorsList", ReplyAction="http://tempuri.org/ILogServices/FilterErrorsListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WcfServiceDSABank.ErrorView>> FilterErrorsListAsync(string query, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogServices/FilterEventsList", ReplyAction="http://tempuri.org/ILogServices/FilterEventsListResponse")]
        System.Collections.Generic.List<WcfServiceDSABank.EventView> FilterEventsList(string source, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogServices/FilterEventsList", ReplyAction="http://tempuri.org/ILogServices/FilterEventsListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WcfServiceDSABank.EventView>> FilterEventsListAsync(string source, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogServices/LogError", ReplyAction="http://tempuri.org/ILogServices/LogErrorResponse")]
        void LogError(string username, string message, string innerException);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogServices/LogError", ReplyAction="http://tempuri.org/ILogServices/LogErrorResponse")]
        System.Threading.Tasks.Task LogErrorAsync(string username, string message, string innerException);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogServices/LogEvent", ReplyAction="http://tempuri.org/ILogServices/LogEventResponse")]
        void LogEvent(string username, string message, string source);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogServices/LogEvent", ReplyAction="http://tempuri.org/ILogServices/LogEventResponse")]
        System.Threading.Tasks.Task LogEventAsync(string username, string message, string source);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogServicesChannel : BankManager.LogServices.ILogServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogServicesClient : System.ServiceModel.ClientBase<BankManager.LogServices.ILogServices>, BankManager.LogServices.ILogServices {
        
        public LogServicesClient() {
        }
        
        public LogServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DeleteError(int id) {
            base.Channel.DeleteError(id);
        }
        
        public System.Threading.Tasks.Task DeleteErrorAsync(int id) {
            return base.Channel.DeleteErrorAsync(id);
        }
        
        public void DeleteEvent(int id) {
            base.Channel.DeleteEvent(id);
        }
        
        public System.Threading.Tasks.Task DeleteEventAsync(int id) {
            return base.Channel.DeleteEventAsync(id);
        }
        
        public System.Collections.Generic.List<WcfServiceDSABank.ErrorView> FilterErrorsList(string query, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end) {
            return base.Channel.FilterErrorsList(query, start, end);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WcfServiceDSABank.ErrorView>> FilterErrorsListAsync(string query, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end) {
            return base.Channel.FilterErrorsListAsync(query, start, end);
        }
        
        public System.Collections.Generic.List<WcfServiceDSABank.EventView> FilterEventsList(string source, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end) {
            return base.Channel.FilterEventsList(source, start, end);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WcfServiceDSABank.EventView>> FilterEventsListAsync(string source, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end) {
            return base.Channel.FilterEventsListAsync(source, start, end);
        }
        
        public void LogError(string username, string message, string innerException) {
            base.Channel.LogError(username, message, innerException);
        }
        
        public System.Threading.Tasks.Task LogErrorAsync(string username, string message, string innerException) {
            return base.Channel.LogErrorAsync(username, message, innerException);
        }
        
        public void LogEvent(string username, string message, string source) {
            base.Channel.LogEvent(username, message, source);
        }
        
        public System.Threading.Tasks.Task LogEventAsync(string username, string message, string source) {
            return base.Channel.LogEventAsync(username, message, source);
        }
    }
}
